#ifndef NEX_CONSTANTS_H
#define NEX_CONSTANTS_H

#define NEX_PHYL_NODE_KEY_BUFFER_SIZE 32
#define NEX_PHYL_NODE_FORTH_CAPACITY_STEP 8

#define NEX_FILE_READ_BUFFER_SIZE 65536

#define NEX_TREE_PATH_MAX_DEPTH 8

#endif
