/*
 *      DiversUtils - Functions to measure diversity
 *
 * Copyright (c) 2024  LISN / Université Paris-Saclay / CNRS  Louis Estève (louis.esteve@universite-paris-saclay.fr)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef MACROCONFIG_H
#define MACROCONFIG_H

#define BFR_SIZE 256
#define MAX_FILES 1024

#ifndef ENABLE_STIRLING
#define ENABLE_STIRLING 1
#endif
#ifndef ENABLE_RICOTTA_SZEIDL
#define ENABLE_RICOTTA_SZEIDL 1
#endif
#ifndef ENABLE_PAIRWISE
#define ENABLE_PAIRWISE 1
#endif
#ifndef ENABLE_LEXICOGRAPHIC
#define ENABLE_LEXICOGRAPHIC 0
#endif
#ifndef ENABLE_CHAO_ET_AL_FUNCTIONAL_DIVERSITY
#define ENABLE_CHAO_ET_AL_FUNCTIONAL_DIVERSITY 1
#endif
#ifndef ENABLE_SCHEINER_SPECIES_PHYLOGENETIC_FUNCTIONAL_DIVERSITY
#define ENABLE_SCHEINER_SPECIES_PHYLOGENETIC_FUNCTIONAL_DIVERSITY 1
#endif
#ifndef ENABLE_LEINSTER_COBBOLD_DIVERSITY
#define ENABLE_LEINSTER_COBBOLD_DIVERSITY 0
#endif
#ifndef ENABLE_FUNCTIONAL_EVENNESS
#define ENABLE_FUNCTIONAL_EVENNESS 0
#endif
#ifndef ENABLE_FUNCTIONAL_DISPERSION
#define ENABLE_FUNCTIONAL_DISPERSION 1
#endif
#ifndef ENABLE_FUNCTIONAL_DIVERGENCE_MODIFIED
#define ENABLE_FUNCTIONAL_DIVERGENCE_MODIFIED 1
#endif

#ifndef ENABLE_DISPARITY_FUNCTIONS
#define ENABLE_DISPARITY_FUNCTIONS 1
#endif
#ifndef ENABLE_NON_DISPARITY_FUNCTIONS
#define ENABLE_NON_DISPARITY_FUNCTIONS 1
#endif

#ifndef ENABLE_SHANNON_WEAVER_ENTROPY
#define ENABLE_SHANNON_WEAVER_ENTROPY 1
#endif
#ifndef ENABLE_GOOD_ENTROPY
#define ENABLE_GOOD_ENTROPY 1
#endif
#ifndef ENABLE_RENYI_ENTROPY
#define ENABLE_RENYI_ENTROPY 1
#endif
#ifndef ENABLE_PATIL_TAILLIE_ENTROPY
#define ENABLE_PATIL_TAILLIE_ENTROPY 1
#endif
#ifndef ENABLE_Q_LOGARITHMIC_ENTROPY
#define ENABLE_Q_LOGARITHMIC_ENTROPY 1
#endif
#ifndef ENABLE_SIMPSON_INDEX
#define ENABLE_SIMPSON_INDEX 1
#endif
#ifndef ENABLE_SIMPSON_DOMINANCE_INDEX
#define ENABLE_SIMPSON_DOMINANCE_INDEX 1
#endif
#ifndef ENABLE_HILL_NUMBER_STANDARD
#define ENABLE_HILL_NUMBER_STANDARD 1
#endif
#ifndef ENABLE_HILL_EVENNESS
#define ENABLE_HILL_EVENNESS 1
#endif
#ifndef ENABLE_BERGER_PARKER_INDEX
#define ENABLE_BERGER_PARKER_INDEX 1
#endif
#ifndef ENABLE_JUNGE1994_PAGE22
#define ENABLE_JUNGE1994_PAGE22 1
#endif
#ifndef ENABLE_BRILLOUIN_DIVERSITY
#define ENABLE_BRILLOUIN_DIVERSITY 1
#endif
#ifndef ENABLE_MCINTOSH_INDEX
#define ENABLE_MCINTOSH_INDEX 1
#endif
#ifndef ENABLE_SW_ENTROPY_OVER_LOG_N_SPECIES_PIELOU1975
#define ENABLE_SW_ENTROPY_OVER_LOG_N_SPECIES_PIELOU1975 1
#endif
#ifndef ENABLE_SW_E_HEIP
#define ENABLE_SW_E_HEIP 1
#endif
#ifndef ENABLE_SW_E_ONE_MINUS_D
#define ENABLE_SW_E_ONE_MINUS_D 1
#endif
#ifndef ENABLE_SW_E_ONE_OVER_LN_D_WILLIAMS1964
#define ENABLE_SW_E_ONE_OVER_LN_D_WILLIAMS1964 1
#endif
#ifndef ENABLE_SW_E_MINUS_LN_D_PIELOU1977
#define ENABLE_SW_E_MINUS_LN_D_PIELOU1977 1
#endif
#ifndef ENABLE_SW_F_2_1_ALATALO1981
#define ENABLE_SW_F_2_1_ALATALO1981 1
#endif
#ifndef ENABLE_SW_G_2_1_MOLINARI1989
#define ENABLE_SW_G_2_1_MOLINARI1989 1
#endif
#ifndef ENABLE_SW_E_BULLA1994
#define ENABLE_SW_E_BULLA1994 1
#endif
#ifndef ENABLE_SW_O_BULLA1994
#define ENABLE_SW_O_BULLA1994 1
#endif
#ifndef ENABLE_SW_E_MCI_PIELOU1969
#define ENABLE_SW_E_MCI_PIELOU1969 1
#endif
#ifndef ENABLE_SW_E_PRIME_CAMARGO1993
#define ENABLE_SW_E_PRIME_CAMARGO1993 1
#endif
#ifndef ENABLE_SW_E_VAR_SMITH_AND_WILSON1996_ORIGINAL
#define ENABLE_SW_E_VAR_SMITH_AND_WILSON1996_ORIGINAL 1
#endif

#ifndef ALPHA_GENERAL
#define ALPHA_GENERAL 1.0
#endif

#ifndef BETA_GENERAL
#define BETA_GENERAL 1.0
#endif

#define GOOD_ALPHA ALPHA_GENERAL
#define GOOD_BETA ALPHA_GENERAL
#define RENYI_ALPHA ALPHA_GENERAL
#define PATIL_TAILLIE_ALPHA ALPHA_GENERAL
#define Q_LOGARITHMIC_Q ALPHA_GENERAL
#define HILL_NUMBER_STANDARD_ALPHA ALPHA_GENERAL
#define HILL_EVENNESS_ALPHA ALPHA_GENERAL
#define HILL_EVENNESS_BETA BETA_GENERAL

#define STIRLING_ALPHA ALPHA_GENERAL
#define STIRLING_BETA BETA_GENERAL
#define RICOTTA_SZEIDL_ALPHA ALPHA_GENERAL
#define CHAO_ET_AL_FUNCTIONAL_DIVERSITY_ALPHA ALPHA_GENERAL
#define SCHEINER_SPECIES_PHYLOGENETIC_FUNCTIONAL_DIVERSITY_ALPHA ALPHA_GENERAL
#define LEINSTER_COBBOLD_DIVERSITY_ALPHA ALPHA_GENERAL

#ifndef ENABLE_MULTITHREADED_MATRIX_GENERATION
#define ENABLE_MULTITHREADED_MATRIX_GENERATION 1
#endif

#ifndef ENABLE_TIMINGS
#define ENABLE_TIMINGS 1
#endif

#ifndef ENABLE_ITERATIVE_DISTANCE_COMPUTATION
#define ENABLE_ITERATIVE_DISTANCE_COMPUTATION 0
#endif
#ifndef ENABLE_MULTITHREADED_ROW_GENERATION
#define ENABLE_MULTITHREADED_ROW_GENERATION 1
#endif
#ifndef ROW_GENERATION_BATCH_SIZE
#define ROW_GENERATION_BATCH_SIZE 16
#endif

#ifndef NUM_MATRIX_THREADS
#define NUM_MATRIX_THREADS 4
#endif
#ifndef NUM_ROW_THREADS
#define NUM_ROW_THREADS 4
#endif
#ifndef NUM_FILE_READING_THREADS
#define NUM_FILE_READING_THREADS 4
#endif

#ifndef ENABLE_NON_DISPARITY_MULTITHREADING
#define ENABLE_NON_DISPARITY_MULTITHREADING 1
#endif

#ifndef ENABLE_SW_E_PRIME_CAMARGO1993_MULTITHREADING
#define ENABLE_SW_E_PRIME_CAMARGO1993_MULTITHREADING 1
#endif

#ifndef SENTENCE_COUNT_RECOMPUTE_STEP
#define SENTENCE_COUNT_RECOMPUTE_STEP 1
#endif
#ifndef ENABLE_SENTENCE_COUNT_RECOMPUTE_STEP
#define ENABLE_SENTENCE_COUNT_RECOMPUTE_STEP 0
#endif
#ifndef SENTENCE_RECOMPUTE_STEP_USE_LOG10
#define SENTENCE_RECOMPUTE_STEP_USE_LOG10 0
#endif
#ifndef SENTENCE_COUNT_RECOMPUTE_STEP_LOG10
#define SENTENCE_COUNT_RECOMPUTE_STEP_LOG10 0.1
#endif

#ifndef DOCUMENT_COUNT_RECOMPUTE_STEP
#define DOCUMENT_COUNT_RECOMPUTE_STEP 1
#endif
#ifndef ENABLE_DOCUMENT_COUNT_RECOMPUTE_STEP
#define ENABLE_DOCUMENT_COUNT_RECOMPUTE_STEP 0
#endif
#ifndef DOCUMENT_RECOMPUTE_STEP_USE_LOG10
#define DOCUMENT_RECOMPUTE_STEP_USE_LOG10 0
#endif
#ifndef DOCUMENT_COUNT_RECOMPUTE_STEP_LOG10
#define DOCUMENT_COUNT_RECOMPUTE_STEP_LOG10 0.1
#endif

#ifndef INPUT_PATH
#define INPUT_PATH "measurement_files.txt"
#endif
#ifndef OUTPUT_PATH
#define OUTPUT_PATH "measurement_output.tsv"
#endif
#ifndef OUTPUT_PATH_TIMING
#define OUTPUT_PATH_TIMING "measurement_output_timing.tsv"
#endif
#ifndef OUTPUT_PATH_MEMORY
#define OUTPUT_PATH_MEMORY "measurement_output_memory.tsv"
#endif

#ifndef ENABLE_OUTPUT_TIMING
#define ENABLE_OUTPUT_TIMING 1
#endif
#ifndef ENABLE_OUTPUT_MEMORY
#define ENABLE_OUTPUT_MEMORY 1
#endif


#ifndef TARGET_COLUMN
#define TARGET_COLUMN UD_MWE
#endif

#ifndef ENABLE_TOKEN_UTF8_NORMALISATION
#define ENABLE_TOKEN_UTF8_NORMALISATION 1
#endif

#ifndef W2V_PATH
#define W2V_PATH "/home/esteve/Documents/thesis/other_repos/word2vec/bin/MWE_S2S_IT_11GB_100d_skip-gram.bin"
#endif

#endif
