#ifndef UNICODE_H
#define UNICODE_H

#define UNICODE_VERSION 15
#define UNICODE_SUBVERSION 1

typedef int32_t unicode_t;

#ifdef DEFINE_UNICODE_CONSTANTS
const unicode_t UNICODE_BASIC_LATIN_BEG = 0x00;
const unicode_t UNICODE_BASIC_LATIN_END = 0x7F;

// UNICODE_LETTER
const unicode_t UNICODE_LATIN_UPPER_BEG = 0x41;
const unicode_t UNICODE_LATIN_UPPER_END = 0x5A;
const unicode_t UNICODE_LATIN_LOWER_BEG = 0x61;
const unicode_t UNICODE_LATIN_LOWER_END = 0x7A;

// UNICODE_NUMBER
const unicode_t UNICODE_NUMBER_BEG = 0x30;
const unicode_t UNICODE_NUMBER_END = 0x39;

// UNICODE_PHONETIC
const unicode_t UNICODE_PHONETIC_EXTENSION_BEG = 0x1D00;
const unicode_t UNICODE_PHONETIC_EXTENSION_END = 0x1DBF;

// UNICODE_PUNCTUATION
const unicode_t UNICODE_LATIN_PUNCTUATION1_BEG = 0x21;
const unicode_t UNICODE_LATIN_PUNCTUATION1_END = 0x2F;
const unicode_t UNICODE_LATIN_PUNCTUATION2_BEG = 0x3A;
const unicode_t UNICODE_LATIN_PUNCTUATION2_END = 0x40;
const unicode_t UNICODE_LATIN_PUNCTUATION3_BEG = 0x5B;
const unicode_t UNICODE_LATIN_PUNCTUATION3_END = 0x6A;
const unicode_t UNICODE_LATIN_PUNCTUATION4_BEG = 0x7B;
const unicode_t UNICODE_LATIN_PUNCTUATION4_END = 0x7E;
const unicode_t UNICODE_GENERAL_PUNCTUATION_BEG = 0x2000;
const unicode_t UNICODE_GENERAL_PUNCTUATION_END = 0x206F;
const unicode_t UNICODE_SUPPLEMENTAL_PUNCTUATION_BEG = 0x2E00;
const unicode_t UNICODE_SUPPLEMENTAL_PUNCTUATION_END = 0x2E31;

// UNICODE_CURRENCY
const unicode_t UNICODE_CURRENCY_BEG = 0x20A0;
const unicode_t UNICODE_CURRENCY_END = 0x20B9;

// UNICODE_EMOTICON
const unicode_t UNICODE_EMOTICON_BEG = 0x01F601;
const unicode_t UNICODE_EMOTICON_END = 0x01F64F;

enum {
    UNICODE_LETTER      = 0,
    UNICODE_NUMBER      = 1,
    UNICODE_PUNCTUATION = 2,
    UNICODE_CURRENCY    = 3,
    UNICODE_EMOTICON    = 4,
    UNICODE_PHONETIC    = 5,
    UNICODE_OTHER       = 6,
};
#endif

#endif
